# Generated by Django 3.2.19 on 2023-06-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
