# Generated by Django 3.2.19 on 2023-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='favorite_place',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='one_important_thing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='top_bucket_list',
            field=models.TextField(blank=True),
        ),
    ]
