# Generated by Django 3.2.19 on 2023-07-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='has_mobility_disability',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='top_bucket_list',
        ),
    ]
