# Generated by Django 3.2.19 on 2023-06-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0002_auto_20230614_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='has_mobility_disability',
            field=models.BooleanField(default=False),
        ),
    ]
