# Generated by Django 3.2.19 on 2023-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0003_traveler_has_mobility_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='favorite_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='one_important_thing',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
