# Generated by Django 3.2.19 on 2023-07-01 09:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BucketlistItem',
            new_name='Bucketlist',
        ),
    ]
