# Generated by Django 3.2.19 on 2023-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20230630_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='post',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
