# Generated by Django 3.2.19 on 2023-06-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_location'),
        ('locations', '0003_auto_20230630_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
